/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author juanc
 */
public class MostrarSocio extends javax.swing.JFrame {

    /**
     * Creates new form Socio
     */
    public MostrarSocio() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelIdSocio = new javax.swing.JLabel();
        labelNombreSocio = new javax.swing.JLabel();
        labelDireccionSocio = new javax.swing.JLabel();
        actualizarSocio = new javax.swing.JButton();
        eliminarSocio = new javax.swing.JButton();
        areaDireccionSocio = new javax.swing.JTextField();
        areaIdSocio = new javax.swing.JTextField();
        areaNombreSocio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 450));
        getContentPane().setLayout(null);

        labelIdSocio.setText("ID Socio");
        getContentPane().add(labelIdSocio);
        labelIdSocio.setBounds(80, 120, 60, 16);

        labelNombreSocio.setText("Nombre");
        getContentPane().add(labelNombreSocio);
        labelNombreSocio.setBounds(80, 170, 50, 16);

        labelDireccionSocio.setText("Direccion");
        getContentPane().add(labelDireccionSocio);
        labelDireccionSocio.setBounds(80, 230, 70, 16);

        actualizarSocio.setText("Actualizar");
        getContentPane().add(actualizarSocio);
        actualizarSocio.setBounds(170, 320, 100, 25);

        eliminarSocio.setText("Eliminar");
        getContentPane().add(eliminarSocio);
        eliminarSocio.setBounds(360, 320, 100, 25);
        getContentPane().add(areaDireccionSocio);
        areaDireccionSocio.setBounds(140, 230, 370, 22);

        areaIdSocio.setEditable(false);
        getContentPane().add(areaIdSocio);
        areaIdSocio.setBounds(140, 120, 370, 22);
        getContentPane().add(areaNombreSocio);
        areaNombreSocio.setBounds(140, 170, 370, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarSocio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarSocio;
    private javax.swing.JTextField areaDireccionSocio;
    private javax.swing.JTextField areaIdSocio;
    private javax.swing.JTextField areaNombreSocio;
    private javax.swing.JButton eliminarSocio;
    private javax.swing.JLabel labelDireccionSocio;
    private javax.swing.JLabel labelIdSocio;
    private javax.swing.JLabel labelNombreSocio;
    // End of variables declaration//GEN-END:variables
}
